version: "3"
services:
  main-reverse-proxy:
    image: traefik
    ports:
      - 443:443
    volumes:
      - ../main-reverse-proxy/traefik.yaml:/traefik.yaml
      - ../main-reverse-proxy/conf:/traefik/conf
