version: "3"
services:
  main-reverse-proxy:
    image: traefik
    ports:
      - 80:80
    volumes:
      - ../main-reverse-proxy/traefik.yaml:/traefik.yaml
      - ../main-reverse-proxy/conf:/traefik/conf

  front:
    build: ../front
    volumes:
      - ../front/ssl:/etc/nginx/certs

  ms-gateway:
    build: ../ms-gateway

  # Microservices
  ms-auth:
    build: ../microservices/ms-auth
    restart: always

  ms-ingredient:
    build: ../microservices/ms-ingredient
    restart: always

  ms-modele:
    build: ../microservices/ms-ingredient
    restart: always

  ms-procede:
    build: ../microservices/ms-ingredient
    restart: always